config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'contacts#main'
  get 'contacts/main-2'
  get 'contacts/resume'
  get 'contacts/portfolio'
  get 'contacts/contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :email, format: {with: /.*@.*/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/contact.html.erb
<div class="site-wrap">
<a href="javascript:void(0)" class="offcanvas-toggle js-offcanvas-toggle">Menu</a>
<div class="offcanvas_menu" id="offcanvas_menu">
<ul class="mb-5">
<li><a href="index.html">Bio</a></li>
<li><a href="portfolio.html">Portfolio</a></li>
<li><a href="resume.html">Resume</a></li>
<li class="active"><a href="contact.html">Contact</a></li>
</ul>
<ul class="social">
<li><a href="#" class="fa fa-twitter"></a></li>
<li><a href="#" class="fa fa-facebook"></a></li>
<li><a href="#" class="fa fa-instagram"></a></li>
</ul>
</br>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>

</div>
<aside style="background-image: url(img/profile_big.jpg);"></aside>
<main>
<a href="index-2.html" class="home-button"><span class="fa fa-home"></span></a>
<h1 class="mb-5">Contact Me</h1>
<form action="#" method="post">
<div class="row mb-4">
<div class="col-md-12">
<input type="text" class="form-control" placeholder="Full Name">
</div>
</div>
<div class="row mb-4">
<div class="col-md-12">
<input type="text" class="form-control" placeholder="Email Address">
</div>
</div>
<div class="row mb-4">
<div class="col-md-12">
<input type="text" class="form-control" placeholder="Phone">
</div>
</div>
<div class="row mb-4">
<div class="col-md-12">
<textarea name="#" id="" class="form-control" placeholder="Write some words of encouragement" cols="30" rows="10"></textarea>
</div>
</div>
<div class="row">
<div class="col-md-12">
<input type="submit" class="btn btn-primary btn-block" value="Send Message">
</div>
</div>
</form>
</main>
</div>

<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>
<script src="js/jquery-3.2.1.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.waypoints.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
<script src="js/main.js"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/main-2.html.erb
<div class="site-wrap">
<a href="#" class="offcanvas-toggle js-offcanvas-toggle">Menu</a>
<div class="offcanvas_menu" id="offcanvas_menu">
<ul class="mb-5">
<li class="active"><a href="index-2.html">Bio</a></li>
<li><a href="portfolio.html">Portfolio</a></li>
<li><a href="resume.html">Resume</a></li>
<li><a href="contact.html">Contact</a></li>
</ul>
<ul class="social">
<li><a href="#" class="fa fa-twitter"></a></li>
<li><a href="#" class="fa fa-facebook"></a></li>
<li><a href="#" class="fa fa-instagram"></a></li>
</ul>
</br>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>

</div>
<aside style="background-image: url(assets/profile_big.jpg);"></aside>
<main>
<h1 class="mb-0">Hi, I'm Kate Woodman</h1>
<div class="mb-5">
<p class="lead mb-3">Web Designer &amp; Developer</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, magnam aut animi, excepturi voluptatum placeat dolor accusantium atque iure! Animi architecto eveniet voluptatum illo ut maiores sed, autem pariatur culpa?</p>
<p>Commodi, neque debitis atque cum quod, culpa repellendus voluptatum voluptatem, molestiae dicta laborum nulla corporis illum, ratione rerum quibusdam ea optio! Consectetur obcaecati facilis esse reprehenderit ipsam, facere dolorem incidunt.</p>
</div>
<p>
<a href="#" class="mr-2 mb-2">Twitter</a>
<a href="#" class="mr-2 mb-2">Facebook</a>
<a href="#" class="mr-2 mb-2">Instagram</a>
</p>

</div>
</main>
</div>

<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>
<script src="assets/jquery-3.2.1.min.js"></script>
<script src="assets/popper.min.js"></script>
<script src="assets/bootstrap.min.js"></script>
<script src="assets/owl.carousel.min.js"></script>
<script src="assets/jquery.waypoints.min.js"></script>
<script src="assets/jquery.countdown.min.js"></script>
<script src="assets/main.js"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

app/views/contacts/main.html.erb
<p id="notice"><%= notice %></p>
<div class="site-wrap">
<a href="javascript:void(0)" class="offcanvas-toggle js-offcanvas-toggle"  style="color: white">Menu</a>
<div class="offcanvas_menu" id="offcanvas_menu">
<ul class="mb-5">
<li class="active"><a href="main_2_path">Bio</a></li>
<li><a href="portfolio.html">Portfolio</a></li>
<li><a href="resume">Resume</a></li>
<li><a href="contact.html">Contact</a></li>
</ul>
<ul class="social">
<li><a href="twitter.com" class="fa fa-twitter"></a></li>
<li><a href="facebook.com" class="fa fa-facebook"></a></li>
<li><a href="instagram.com" class="fa fa-instagram"></a></li>
</ul>
</br>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>

</div>
<aside style="background-image: url(assets/profile_big.svg);"></aside>
<main>
<h1 class="mb-0">Hi, I'm Itachi Uchiha</h1>
<div class="mb-5">
<p class="lead mb-3">Web Designer &amp; Developer</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, magnam aut animi, excepturi voluptatum placeat dolor accusantium atque iure! Animi architecto eveniet voluptatum illo ut maiores sed, autem pariatur culpa?</p>
<p>Commodi, neque debitis atque cum quod, culpa repellendus voluptatum voluptatem, molestiae dicta laborum nulla corporis illum, ratione rerum quibusdam ea optio! Consectetur obcaecati facilis esse reprehenderit ipsam, facere dolorem incidunt.</p>
</div>
<p>
<a href="#" class="mr-2 mb-2">Twitter</a>
<a href="#" class="mr-2 mb-2">Facebook</a>
<a href="#" class="mr-2 mb-2">Instagram</a>
</p>

</div>
</main>
</div>

<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>
<script src="assets/jquery-3.2.1.min.js"></script>
<script src="assets/popper.min.js"></script>
<script src="assets/bootstrap.min.js"></script>
<script src="assets/owl.carousel.min.js"></script>
<script src="assets/jquery.waypoints.min.js"></script>
<script src="assets/jquery.countdown.min.js"></script>
<script src="assets/main.js"></script>

<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script> -->
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/portfolio.html.erb
<div class="site-wrap">
<a href="javascript:void(0)" class="offcanvas-toggle js-offcanvas-toggle">Menu</a>
<div class="offcanvas_menu" id="offcanvas_menu">
<ul class="mb-5">
<li><a href="index.html">Bio</a></li>
<li class="active"><a href="portfolio.html">Portfolio</a></li>
<li><a href="resume.html">Resume</a></li>
<li><a href="contact.html">Contact</a></li>
</ul>
<ul class="social">
<li><a href="#" class="fa fa-twitter"></a></li>
<li><a href="#" class="fa fa-facebook"></a></li>
<li><a href="#" class="fa fa-instagram"></a></li>
</ul>
</br>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>

</div>
<aside style="background-image: url(img/profile_big.jpg);"></aside>
<main>
<a href="index-2.html" class="home-button"><span class="fa fa-home"></span></a>
<h1 class="mb-5">Portfolio</h1>
<div class="mb-5">
<ul class="portfolio-list">
<li>
<a href="#">
<img src="img/img_1.jpg" alt="">
<div class="text">
<h3>Project Name</h3>
<span>Visit Website</span>
</div>
</a>
</li>
<li>
<a href="#">
<img src="img/img_2.jpg" alt="">
<div class="text">
<h3>Project Name</h3>
<span>Visit Website</span>
</div>
</a>
</li>
<li>
<a href="#">
<img src="img/img_3.jpg" alt="">
<div class="text">
<h3>Project Name</h3>
<span>Visit Website</span>
</div>
</a>
</li>
</ul>
</div>
</main>
</div>

<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>
<script src="js/jquery-3.2.1.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.waypoints.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
<script src="js/main.js"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

app/views/contacts/resume.html.erb
<div class="site-wrap">
<a href="javascript:void(0)" class="offcanvas-toggle js-offcanvas-toggle">Menu</a>
<div class="offcanvas_menu" id="offcanvas_menu">
<ul class="mb-5">
<!-- <li><a href="index.html">Bio</a></li> -->
<li><%= link_to 'Bio', main_contacts_path %></li>
<li><%= link_to 'Portfolio', portfolio_contacts_path %></li>
<li><%= link_to 'Bio', main_contact_path %></li>
<li><a href="portfolio.html">Portfolio</a></li>
<li class="active"><a href="resume.html">Resume</a></li>
<li><a href="contact.html">Contact</a></li>
</ul>
<ul class="social">
<li><a href="#" class="fa fa-twitter"></a></li>
<li><a href="#" class="fa fa-facebook"></a></li>
<li><a href="#" class="fa fa-instagram"></a></li>
</ul>
</br>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>

</div>
<aside style="background-image: url(img/profile_big.jpg);"></aside>
<main>
<a href="index-2.html" class="home-button"><span class="fa fa-home"></span></a>
<h1 class="mb-5">Experience</h1>
<div class="mb-5">
<ul class="resume-list">
<li>
<h3>Product Designer, Google</h3>
<p class="date">Sep 2017 - Present</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint dolorum dolore culpa libero delectus excepturi! Repellat dolore, sapiente officia quod.</p>
</li>
<li>
<h3>User Experience Director, Facebook</h3>
<p class="date">Jan 2016 - Sep 2017</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint dolorum dolore culpa libero delectus excepturi! Repellat dolore, sapiente officia quod.</p>
</li>
<li>
<h3>Mobile Application Designer, Yahoo</h3>
<p class="date">Nov 2015 - Jan 2016</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint dolorum dolore culpa libero delectus excepturi! Repellat dolore, sapiente officia quod.</p>
</li>
<li>
<h3>Product Designer, Medium</h3>
<p class="date">Feb 2013 - Nov 2015</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint dolorum dolore culpa libero delectus excepturi! Repellat dolore, sapiente officia quod.</p>
</li>
</ul>
</div>
<h1 class="mb-5">Education</h1>
<div class="mb-5">
<ul class="resume-list">
<li>
<h3>Harvard University</h3>
<p class="date">2010 - 2014</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint dolorum dolore culpa libero delectus excepturi! Repellat dolore, sapiente officia quod.</p>
</li>
</ul>
</div>
</main>
</div>

<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>
<script src="js/jquery-3.2.1.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.waypoints.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
<script src="js/main.js"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolioweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>